name: olpaka
description: "A Flutter frontend app for Ollama"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.4.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Markdown
  markdown_widget: ^2.3.2+6

  # Dependency Injection
  get_it: ^7.7.0

  # Navigation
  go_router: ^14.1.3

  # Google Fonts
  google_fonts: ^6.2.1

  # HTTP Client
  http: ^1.2.1
  fetch_client: ^1.1.1

  # Logging
  logger: ^2.3.0

  # MVVM
  stacked: ^3.4.2

  # Localization
  intl: ^0.19.0

  # Url launcher
  url_launcher: ^6.2.6

  # Shared Preferences
  shared_preferences: ^2.2.3

  # App version
  package_info_plus: ^8.0.0

  # Firebase
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.0

flutter_localizations:
  sdk: flutter
  intl_utils: ^2.8.7

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
