name: Pull Request
run-name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Unit test
        run: ./gradlew desktopTest

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Generate test report
          only-summary: 'true'
          path: 'composeApp/build/test-results/**/*.xml'
          reporter: java-junit

      - name: Build Web app
        env:
          FIREBASE_WEB_CONFIG_JSON: ${{ secrets.FIREBASE_WEB_CONFIG_JSON }}
          VERSION_NAME: development
          BASE_HREF: ${{ vars.BASE_HREF }}
        run: |
          ./gradlew :composeApp:wasmJsBrowserDistribution -Pbuildkonfig.flavor=release

      - name: Upload web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OlpakaWeb
          path: composeApp/build/dist/wasmJs/productionExecutable/*

      - name: Upload desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OlpakaDesktop
          path: composeApp/build/libs/*