name: Pull Request
run-name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: ./gradlew allTests

      - name: Upload desktop test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Desktop test report
          only-summary: 'true'
          path: 'composeApp/build/test-results/desktopTest/*.xml'
          reporter: java-junit
          list-tests: 'failed'

      - name: Upload android debug test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android debug test report
          only-summary: 'true'
          path: 'composeApp/build/test-results/testDebugUnitTest/*.xml'
          reporter: java-junit
          list-tests: 'failed'

      - name: Upload android release test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android release test report
          only-summary: 'true'
          path: 'composeApp/build/test-results/testReleaseUnitTest/*.xml'
          reporter: java-junit
          list-tests: 'failed'

      - name: Upload web test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Web test report
          only-summary: 'true'
          path: 'composeApp/build/test-results/wasmJsBrowserTest/*.xml'
          reporter: java-junit
          list-tests: 'failed'

      - name: Build Web app
        env:
          FIREBASE_WEB_CONFIG_JSON: ${{ secrets.FIREBASE_WEB_CONFIG_JSON }}
          VERSION_NAME: development
          BASE_HREF: ${{ vars.BASE_HREF }}
        run: |
          ./gradlew :composeApp:wasmJsBrowserDistribution -Pbuildkonfig.flavor=release

      - name: Upload web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OlpakaWeb
          path: composeApp/build/dist/wasmJs/productionExecutable/*
